apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h3gzq4ad5-go 
  janus-idp.io/tekton: h3gzq4ad5-go
  backstage.io/kubernetes-id: h3gzq4ad5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h3gzq4ad5-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml